const BEYBLADES = [
  {
    id: 'sword-dran',
    name: 'Sword Dran 3-60F',
    type: 'Attack',
    color: '#2563eb',
    secondary: '#dc2626',
    accent: '#ffffff',
    bladeStyle: 'attack',
    emblem: 'dragon',
    stats: { attack: 88, defense: 50, stamina: 55, speed: 82 },
    fanTip: 'Jaxon Cross\'s signature Bey! Flat-tipped bit engages the rail for Xtreme Dashes with powerful blade attacks.',
    description: 'The iconic Attack Type from Beyblade X. Right-spinning with devastating flat-tip dash potential.'
  },
  {
    id: 'dagger-dran',
    name: 'Dagger Dran 4-60R',
    type: 'Attack',
    color: '#b91c1c',
    secondary: '#1e1b4b',
    accent: '#fbbf24',
    bladeStyle: 'attack',
    emblem: 'dragon',
    stats: { attack: 90, defense: 48, stamina: 52, speed: 85 },
    fanTip: 'Featured in the Xtreme Battle Set — a Takara Tomy-designed Attack Type with authentic die-cast metal parts.',
    description: 'Aggressive dagger-shaped blades built for crushing rail-accelerated collisions.'
  },
  {
    id: 'buster-dran',
    name: 'Buster Dran',
    type: 'Attack',
    color: '#dc2626',
    secondary: '#ffd700',
    accent: '#fff',
    bladeStyle: 'attack',
    emblem: 'dragon',
    stats: { attack: 95, defense: 42, stamina: 48, speed: 78 },
    fanTip: 'The evolved Dran line — maximum offensive power for bladers who never hold back.',
    description: 'Heavy-hitting Attack Type with gold-accented blades for burst finish potential.'
  },
  {
    id: 'arrow-wizard',
    name: 'Arrow Wizard 4-80B',
    type: 'Stamina',
    color: '#7c3aed',
    secondary: '#4c1d95',
    accent: '#e9d5ff',
    bladeStyle: 'stamina',
    emblem: 'wizard',
    stats: { attack: 50, defense: 65, stamina: 92, speed: 55 },
    fanTip: 'Multi Nana-iro\'s Bey — generates strong centrifugal force to outlast any opponent.',
    description: 'Right-spinning Stamina Type. Keeps spinning long after aggressive blades burn out.'
  },
  {
    id: 'wand-wizard',
    name: 'Wand Wizard',
    type: 'Stamina',
    color: '#a855f7',
    secondary: '#581c87',
    accent: '#faf5ff',
    bladeStyle: 'stamina',
    emblem: 'wizard',
    stats: { attack: 48, defense: 68, stamina: 95, speed: 50 },
    fanTip: 'Wizard series fans love the smooth spin and magical centrifugal endurance.',
    description: 'Elegant Stamina blade with wand-shaped energy layer for maximum spin time.'
  },
  {
    id: 'scythe-incendio',
    name: 'Scythe Incendio 4-60T',
    type: 'Balance',
    color: '#ea580c',
    secondary: '#dc2626',
    accent: '#fef3c7',
    bladeStyle: 'balance',
    emblem: 'incendio',
    stats: { attack: 72, defense: 68, stamina: 75, speed: 70 },
    fanTip: 'Robin Kazami\'s Bey — tapered bit balances early attack power with endurance.',
    description: 'Balance Type with scythe-shaped blades. Attack early, endure late.'
  },
  {
    id: 'chain-incendio',
    name: 'Chain Incendio',
    type: 'Balance',
    color: '#f97316',
    secondary: '#991b1b',
    accent: '#fcd34d',
    bladeStyle: 'balance',
    emblem: 'incendio',
    stats: { attack: 70, defense: 72, stamina: 78, speed: 65 },
    fanTip: 'Chain-link blade design absorbs impact while maintaining spin — perfect for Robin\'s growth arc.',
    description: 'Linked blade segments give this Balance Type unpredictable collision angles.'
  },
  {
    id: 'hammer-incendio',
    name: 'Hammer Incendio',
    type: 'Balance',
    color: '#c2410c',
    secondary: '#7f1d1d',
    accent: '#fde68a',
    bladeStyle: 'balance',
    emblem: 'incendio',
    stats: { attack: 78, defense: 65, stamina: 70, speed: 62 },
    fanTip: 'Hammer-shaped contact points deliver punishing hits without sacrificing too much stamina.',
    description: 'Heavy Balance Type — each collision hits like a hammer blow.'
  },
  {
    id: 'helm-knight',
    name: 'Helm Knight 3-80N',
    type: 'Defense',
    color: '#64748b',
    secondary: '#1e40af',
    accent: '#e2e8f0',
    bladeStyle: 'defense',
    emblem: 'knight',
    stats: { attack: 45, defense: 95, stamina: 80, speed: 42 },
    fanTip: 'Shock-absorbing blades dampen your opponent\'s attack — the ultimate wall.',
    description: 'Defense Type with helm-shaped energy layer. Deflects and absorbs impact.'
  },
  {
    id: 'lance-knight',
    name: 'Lance Knight',
    type: 'Defense',
    color: '#475569',
    secondary: '#312e81',
    accent: '#c7d2fe',
    bladeStyle: 'defense',
    emblem: 'knight',
    stats: { attack: 50, defense: 92, stamina: 78, speed: 45 },
    fanTip: 'Lance Knight users control the center — let opponents crash into your defenses.',
    description: 'Lance-pointed Defense blade that punishes reckless attackers.'
  },
  {
    id: 'saber-samurai',
    name: 'Saber Samurai',
    type: 'Attack',
    color: '#dc2626',
    secondary: '#f8fafc',
    accent: '#fca5a5',
    bladeStyle: 'attack',
    emblem: 'samurai',
    stats: { attack: 86, defense: 55, stamina: 58, speed: 75 },
    fanTip: 'Tenka Shiroboshi\'s Bey — Seiken techniques unleash power beyond ordinary Pros.',
    description: 'Samurai-inspired Attack Type with razor-sharp blade contact points.'
  },
  {
    id: 'soar-phoenix',
    name: 'Soar Phoenix 9-60GF',
    type: 'Attack',
    color: '#dc2626',
    secondary: '#ffd700',
    accent: '#fff7ed',
    bladeStyle: 'attack',
    emblem: 'phoenix',
    stats: { attack: 92, defense: 48, stamina: 50, speed: 88 },
    fanTip: 'Red painted heavy metal blades with flat gear for powerful string-launcher attacks!',
    description: 'Deluxe Attack Type — phoenix wings deliver soaring burst potential.'
  },
  {
    id: 'steel-samurai',
    name: 'Steel Samurai 4-80T',
    type: 'Balance',
    color: '#71717a',
    secondary: '#27272a',
    accent: '#d4d4d8',
    bladeStyle: 'balance',
    emblem: 'samurai',
    stats: { attack: 68, defense: 75, stamina: 82, speed: 58 },
    fanTip: 'Tapered bit provides early attack power AND endurance — a true samurai\'s patience.',
    description: 'Steel-forged Balance Type. Methodical, precise, unstoppable.'
  },
  {
    id: 'talon-ptera',
    name: 'Talon Ptera 3-80B',
    type: 'Stamina',
    color: '#059669',
    secondary: '#0d9488',
    accent: '#a7f3d0',
    bladeStyle: 'stamina',
    emblem: 'ptera',
    stats: { attack: 42, defense: 60, stamina: 98, speed: 48 },
    fanTip: 'Downward-pointing blades slow opponents, giving your stamina time to outlast them.',
    description: 'Pterosaur Stamina Type — glides through the stadium with endless spin.'
  },
  {
    id: 'knife-shinobi',
    name: 'Knife Shinobi 4-80HN',
    type: 'Defense',
    color: '#581c87',
    secondary: '#1e1b4b',
    accent: '#c084fc',
    bladeStyle: 'defense',
    emblem: 'shinobi',
    stats: { attack: 55, defense: 90, stamina: 72, speed: 52 },
    fanTip: 'Strong center of gravity keeps Shinobi centered while deflecting every attack.',
    description: 'Ninja Defense Type — stays planted and turns aggression against opponents.'
  },
  {
    id: 'keel-shark',
    name: 'Keel Shark 3-80F',
    type: 'Attack',
    color: '#0284c7',
    secondary: '#334155',
    accent: '#bae6fd',
    bladeStyle: 'attack',
    emblem: 'shark',
    stats: { attack: 88, defense: 52, stamina: 55, speed: 80 },
    fanTip: 'Attacks from a low position directly at your opponent\'s ratchet — aim for the burst!',
    description: 'Shark-fin Attack Type built for low-angle knockout strikes.'
  },
  {
    id: 'tusk-mammoth',
    name: 'Tusk Mammoth 3-60T',
    type: 'Balance',
    color: '#78716c',
    secondary: '#44403c',
    accent: '#d6d3d1',
    bladeStyle: 'balance',
    emblem: 'mammoth',
    stats: { attack: 65, defense: 78, stamina: 85, speed: 40 },
    fanTip: 'From the Xtreme Battle Set — heavy tusks trade speed for devastating momentum.',
    description: 'Massive Balance Type. Slow to start, impossible to stop.'
  }
];

const BATTLEFIELDS = [
  {
    id: 'miami',
    name: 'Miami Sunset Bay',
    emoji: '🌴',
    month: 'Month 1 — Where it all began',
    gradient: 'linear-gradient(135deg, #ff6b6b, #ffd93d, #6bcbff)',
    description: 'Palm trees, ocean breeze, and golden sunsets — where our story first sparked under the Miami sky. Fast, flashy battles on sun-kissed sand.',
    arenaColor: '#e8c49a',
    accentColor: '#ff6b6b',
    skyTop: '#ff7e5f',
    skyMid: '#feb47b',
    skyBottom: '#6bcbff',
    floorColor: '#d4a574',
    particles: 'palm'
  },
  {
    id: 'pittsburgh',
    name: 'Pittsburgh Love Lock',
    emoji: '💕',
    month: 'Month 2 — Steel City romance',
    gradient: 'linear-gradient(135deg, #667eea, #764ba2, #f093fb)',
    description: 'Our romantic dates in the Steel City — bridges, city lights, and steady hearts. Strategic, patient battles where every move is made with love.',
    arenaColor: '#3d3d5c',
    accentColor: '#f093fb',
    skyTop: '#1a1a2e',
    skyMid: '#4a3f6b',
    skyBottom: '#764ba2',
    floorColor: '#2d2d44',
    particles: 'hearts'
  },
  {
    id: 'texas',
    name: 'Texas Star Arena',
    emoji: '🤠',
    month: 'Month 3 — Go big or go home',
    gradient: 'linear-gradient(135deg, #f7971e, #ffd200, #c850c0)',
    description: 'Big skies, bold moves, and wide-open spaces — just like our Texas adventures. High-impact collisions and fearless all-out attacks.',
    arenaColor: '#c87941',
    accentColor: '#f7971e',
    skyTop: '#ff6b35',
    skyMid: '#f7c948',
    skyBottom: '#e85d04',
    floorColor: '#b5651d',
    particles: 'stars'
  },
  {
    id: 'longdistance',
    name: 'Miles Apart, Hearts Together',
    emoji: '💌',
    month: 'Month 4 — Distance can\'t break us',
    gradient: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
    description: 'Long distance, but our love stays strong. Every hit lands with heart from afar — proof that miles mean nothing when the bond is real. Fight with love that bridges any gap.',
    arenaColor: '#2a2a4a',
    accentColor: '#9b59b6',
    skyTop: '#0f0c29',
    skyMid: '#302b63',
    skyBottom: '#24243e',
    floorColor: '#1a1a35',
    particles: 'hearts'
  }
];

const TUTORIAL_SLIDES = [
  {
    icon: '🎮',
    title: 'Move Your Blade',
    text: 'Use the <span class="tutorial-highlight">arrow keys</span> to move your Beyblade around the stadium. Up, down, left, and right — dodge opponents and chase them down!',
    keys: ['↑', '↓', '←', '→']
  },
  {
    icon: '⚡',
    title: 'Power Up!',
    text: 'Hold the <span class="tutorial-highlight">space bar</span> to charge your spin power. Release at full charge for a devastating burst attack that deals extra damage on collision!',
    keys: ['SPACE']
  },
  {
    icon: '❤️',
    title: 'Watch Your Health',
    text: 'Your <span class="tutorial-highlight">life hearts</span> are shown at the top left. Each collision costs health — lose all hearts and the round is over. Win <span class="tutorial-highlight">2 out of 3 rounds</span> to claim victory!',
    keys: []
  }
];
